---
#tasks for cluster_setup
 - name: include user defined variables
   include_vars: user_vars.yaml

 - name: cloudmesh configuration
   command: echo "Cloudmesh Configuration"

 - name: set refresh cloudmesh on
   command: cm refresh on

 - name: add key to cloudmesh database
   command: cm key add {{ username }} --source={{ local_home}}{{ key_path }}

 - name: set default cloud
   command: cm default cloud={{ cloud }}

 - name: set default user
   command: cm default user={{ username }}

 - name: check vm_machine setup info       
   command: cm info

 - name: upload key to cloud server
   command: cm key upload

 - name: check security group setting
   command: cm secgroup list

 - name: upload security group setting to cloud server
   command: cm secgroup upload
