---
#tasks to deploy hadoop and Spark cluster
 - name: include user defined variables
   include_vars: user_vars.yaml

 - name: define cluster
   command: cm cluster define --count {{ count }} --image "{{ image_name }}" --flavor "{{ flavor }}"

 - name: define hadoop stack
   command: cm hadoop define {{ addons }}

 - name: check defined cluster
   command: cm cluster avail

 - name: check defined hadoop stack
   command: cm hadoop avail

 - name: hadoop stack sync from github
   shell: cm hadoop sync

 - name: deploy hadoop cluster
   shell: cm hadoop deploy

 - name: establish connectivity between nodes
   shell: cm cluster cross_ssh
